name: Daily Email Reminder

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8 AM UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    environment: email_reminder  # Replace with your actual environment name if different

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the mail sender script
        run: python email_utils.py
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
